[package]
name = "antimony-core"
version = "0.1.0"
edition = "2021"

[dependencies]
glam = { version = "0.29", features = ["rand"] }
rand = "0.8"
serde = { version = "1.0", features = ["derive"] }
getrandom = { version = "0.2", features = ["js"] }
