[package]
name = "shivam"
version = "0.1.0"
edition = "2021"

[dependencies]
dna = { path = "../DNA" }
serde.workspace = true
serde_json.workspace = true

# For celestial events API
# reqwest = { version = "0.11", features = ["json"] }
